### ISSUE TITLE
Error loading native library: Unable to load library 'msvcr120'

### ISSUE THREAD

**Issue by jholderieath** [ropensci/nlrx#28]
I am getting the following error, which I believe to be with `nlrx`, because the model will run in NetLogo now that the R extension from NetLogo issues have been worked out. The r.jar and jna-4.2.2.jar files are both there.  

nlrx is running the simulation in Netlogo which uses a nonlinear solver from GAMS in R to choose activities. I have successfully used the model in a linux environment.

```
C:\Users\zejas\AppData\Roaming\NetLogo\6.1\extensions\r>ls
GPL.txt  jna-4.2.2.jar  models  r.jar  user.properties
```
![image](https://user-images.githubusercontent.com/9774698/62967412-be425e80-bdbd-11e9-9ddd-45e88f62e3ea.png)

```
> utils::sessionInfo() 
R version 3.5.3 (2019-03-11) 
Platform: x86_64-w64-mingw32/x64 (64-bit) 
Running under: Windows 10 x64 (build 17763)  

Matrix products: default  

locale: [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252      

attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       

other attached packages: [1] nlrx_0.2.0           RevoUtils_11.0.3     RevoUtilsMath_11.0.0  

loaded via a namespace (and not attached):  [1] Rcpp_1.0.1       XML_3.98-1.19    crayon_1.3.4     dplyr_0.8.0.1    assertthat_0.2.1 R6_2.4.0          [7] magrittr_1.5     pillar_1.3.1     miscTools_0.6-22 rlang_0.3.4      rstudioapi_0.10  tools_3.5.3      [13] readr_1.3.1      glue_1.3.1       purrr_0.3.2      hms_0.4.2        compiler_3.5.3   pkgconfig_2.0.2  [19] tidyselect_0.2.5 tibble_2.1.1
>



> results <- run_nl_one(nl, seed=1,siminputrow = 1)
Error loading native library: Unable to load library 'msvcr120': Native library (win32-x86-64/msvcr120.dll) not found in resource path ([file:/C:/Users/zejas/AppData/Roaming/NetLogo/6.1/extensions/r/r.jar, file:/C:/Users/zejas/AppData/Roaming/NetLogo/6.1/extensions/r/jna-4.2.2.jar, file:/C:/Users/zejas/AppData/Roaming/NetLogo/6.1/extensions/r/r.jar])
java.lang.UnsatisfiedLinkError: Unable to load library 'msvcr120': Native library (win32-x86-64/msvcr120.dll) not found in resource path ([file:/C:/Users/zejas/AppData/Roaming/NetLogo/6.1/extensions/r/r.jar, file:/C:/Users/zejas/AppData/Roaming/NetLogo/6.1/extensions/r/jna-4.2.2.jar, file:/C:/Users/zejas/AppData/Roaming/NetLogo/6.1/extensions/r/r.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at org.nlogo.extension.r.Entry.<clinit>(Entry.java:100)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nlogo.workspace.JarLoader.extensionClassManager(JarLoader.scala:48)
	at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
	at scala.Option.getOrElse(Option.scala:138)
	at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
	at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
	at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
	at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
	at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
	at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
	at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
	at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
	at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
	at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:43)
	at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
	at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:50)
	at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:539)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:506)
	at org.nlogo.headless.Main$.newWorkspace$1(Main.scala:18)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:21)
	at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:12)
	at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:12)
	at scala.Option.foreach(Option.scala:274)
	at org.nlogo.headless.Main$.main(Main.scala:12)
	at org.nlogo.headless.Main.main(Main.scala)
```

**Comment by nldoc** [comment]
Unfortunately I have not seen this error before. However, I assume that this is more a problem with your system setup than with the package itself. I already saw that you have opened a question on [stackexchange](https://superuser.com/questions/1471299/error-loading-native-library-unable-to-load-library-msvcr120-r-netlogo) where you already accepted an answer as correct. Is it true that this answer solved your problem? If yes, I can link it here and close this issue, right?
Cheers, nldoc

**Comment by jholderieath** [comment]
Yes. That is correct. I am quite sorry, I thought I had closed this.

**Comment by nldoc** [comment]
no worries, I am glad that you could solve your problem 👍
